### ISSUE TITLE
Compile extra helper functions during compilation of main function

### ISSUE THREAD

**Issue by EduardoGRocha** [tetzank/coat#2]
Hi, 

I have the problem that for operators like Sort and Join one probably wants to compile the compare/hash functions. For asmjit backend doing something like bellow works fine:
(EDITED)
```
coat::Function<coat::runtimeasmjit,compare_function_t > compare_f(fn.asmrt, "compare_f");
        {
            auto [a, b] = compare_f.getArguments("a", "b");
            // TODO haven't found a nice way of returning 0/1 for compare functions
            coat::if_then_else(compare_f, a < b, [&] {
                    coat::ret(compare_f, one);
                }, [&] {
                    coat::ret(compare_f, zero);
            });
        }
        // Saves the function pointer for later usage
        SortOperator::compiled_compare = compare_f.finalize();

     ...
     static void call_sort(start, end) {
         std::sort(start, end, SortOperator.compiled_compare);
     }
```
Then later I call
```coat::FunctionCall(fn, SortOperator::call_sort, "call_sort", start, end);```

For LLVM it doesn't work as using the same runtime for both functions will cause the first `finalize()` call to terminate it for both. Also, doing:
```
coat::runtimellvmjit 
coat::Function<coat::runtimellvmjit,compare_function_t > compare_f(llvmrt, "compare_f");
        {...}
        SortOperator::compiled_compare = compare_f.finalize();
        coat::FunctionCall(fn, SortOperator::call_sort, "call_sort", start, end);
```
doesn't work either. The generated functions `f` and `compare_f` keep calling each other.

Internal Functions wouldn't help either because I can't pass it to an external function.

Do you see any way out of it? It would really mess my code if I had to first generate the helper functions separately and then generate the query function.

**Comment by EduardoGRocha** [comment]
I found out that my issue was that llvmrt was going out of scope (and therefore being deleted). The bad part is that the error which we get (returning the same pointer for both functions which points to a mix of both functions) is very hard to understand. 

Still, I wonder if it would be possible to have it the way asmjit does
`coat::Function<coat::runtimeasmjit,compare_function_t > compare_f(fn.asmrt, "compare_f");` 
So here we can use the same run time to create all functions.

**Comment by tetzank** [comment]
Mhmm, I thought, I fixed that. It should be possible to generate two functions with the same runtime object and have the functions call each other, see the fibonacci.cpp example.

assemble_selfcall generates a recursive function which calls itself:
https://github.com/tetzank/coat/blob/d61342fdf956fd35a3c615769b82758db9ba15d7/fibonacci.cpp#L19

assemble_crosscall just calls the recursive function:
https://github.com/tetzank/coat/blob/d61342fdf956fd35a3c615769b82758db9ba15d7/fibonacci.cpp#L33

It might be that your function name is incorrect in the call. LLVM does symbol lookup, ignoring the function pointer. Asmjit just takes the address of the function pointer and jumps there, ignoring the function name.

That's why I'm surprised that the following line works for you with LLVM:
```cpp
coat::FunctionCall(fn, std::sort, "call_sort", start, end, compare_f)
```

I actually want to get rid of the symbol lookup in LLVM as we already have the address in the function pointer. But that's how it currently works.

**Comment by EduardoGRocha** [comment]
Hi, I edited my comment, it was a bit wrong.

My problem is that the compare function is passed as a parameter to another function. In the case of Fibonacci, you call an internal function from the generated function. In my case I want my generated function to call std::sort, passing another generated function as argument.

Since coat doesn't yet support passing function as arguments, my solution was to compile the help function to its pointer and save it somewhere else (as a static varible). Then during the call (so inside call_sort) I pass this pointer to std::sort. So I'm not using the AddFunction, but rather creating a new Function<> object.

The problem is that you can't have 2 coat::Function<> objects created at the same time using the same llvmrt. Even though it works with asmjit.

**Comment by EduardoGRocha** [comment]
I created a small sample here. The llvm runtime has a small hack to return the pointer of the called function when using function call, since calling external functions is broken in LLVM.

```
#include <vector>
#include <algorithm>

#include <coat/Function.h>
#include <coat/ControlFlow.h>
#include <coat/Ptr.h>

#include "process_engine/infra/column_type.h"

using func_t = void (*) ();
using compare_f_t = uint64_t (*) (uint64_t a, uint64_t b);

compare_f_t compiled_compare_f;


void call_sort(uint64_t* start, uint64_t* end) {
    std::sort(start, end, compiled_compare_f);
}

int main(int argc, char *argv[]){
#ifdef ENABLE_ASMJIT
// Works for asmjit backend
    coat::runtimeasmjit asmrt;
    coat::Function<coat::runtimeasmjit,func_t> fn(asmrt);
    using CC = ::asmjit::x86::Compiler;
    coat::Function<coat::runtimeasmjit, compare_f_t> compare_f(asmrt);
#endif
//#ifdef ENABLE_LLVMJIT
//    coat::runtimellvmjit::initTarget();
//    coat::runtimellvmjit llvmrt;
//    llvmrt.setOptLevel(3);
//    using CC = llvm::IRBuilder<>;
//    coat::Function<coat::runtimellvmjit,func_t> fn(llvmrt);
//    coat::Function<coat::runtimellvmjit, compare_f_t> compare_f(llvmrt);
// Hacked LLVM runtime to store function pointers since call is broken
//    llvmrt.register_runtime_function("call_sort", reinterpret_cast<void*>(call_sort));
//#endif
    std::vector<uint64_t> vector = {4, 3, 2, 1, 0};
    auto start = vector.data();
    auto end = vector.data() + 5;


    {
        auto coat_start = coat::Ptr<CC, uint64_t*>(fn, start, "coat_start");
        auto coat_end = coat::Ptr<CC, uint64_t*>(fn, end, "coat_end");

        {
            auto [a, b] = compare_f.getArguments("a", "b");
            auto zero = coat::Value<CC, uint64_t>(compare_f, uint64_t(0), "zero");
            auto one = coat::Value<CC, uint64_t>(compare_f, uint64_t(1), "one");

            // Coat doesn't support Condition.evaluate()
            coat::if_then_else(compare_f, a < b, [&] {
                coat::ret(compare_f, one);
            }, [&] {
               coat::ret(compare_f, zero);
            });
        }
        compiled_compare_f = compare_f.finalize();
        coat::FunctionCall(fn, call_sort, "call_sort", coat_start, coat_end);

        // LLVM needs a return type
        coat::ret(fn);
    }

    auto f = fn.finalize();
    f();
    for (const auto &val : vector) {
        std::cout << val << ", ";
    }
    return 0;
}
```

In this case one could move the compare function generation to after fn.finalize() is called. However, in a real database, this sort operator is embedded in a tree, which makes it moving to after fn.finalize() hard.

**Comment by tetzank** [comment]
Ok, now I understand the problem. I haven't thought about this constellation, but it makes sense. Let me see if I can find a solution in the next days.

LLVM can call external functions if you compile the host program they are in with -rdynamic, otherwise the symbol lookup will fail. That's the main reason I want to get rid of symbol lookup... It's a pain.

**Comment by EduardoGRocha** [comment]
Marking as resolved as the recent updates have addressed it
